version: '3.3'
services:
  checker:
    build: ./checker
    ports:
      - "80:5000"
    volumes:
      - ./checker:/checker
      - ./uploads:/checker/uploads
    env_file:
      - env
    restart: always
    depends_on:
      - postgres
    networks:
      - hackathon

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data
    env_file:
      - env
    restart: always
    hostname: postgres.service
    networks:
      hackathon:
        aliases:
          - postgres.service
networks:
  hackathon:
    driver: bridge